@host = http://localhost:8080
# @host = https://collected-193006.appspot.com

###
GET {{host}}/

###
POST {{host}}/user-credentials

###
PUT {{host}}/1/org:RoyalIcing
Content-Type: application/json

{}

###
PUT {{host}}/1/org:RoyalIcing/channel:design
Content-Type: application/json

###
GET {{host}}/1/org:RoyalIcing/channel:design

###
POST {{host}}/1/org:RoyalIcing/channel:design/posts
Content-Type: application/json

{
  "markdownSource": "# This is a test!\n\n- A list\n- of\n- items\n"
}


###
GET {{host}}/1/org:RoyalIcing/channel.id:aghkZXZ-Tm9uZXInCxIDT3JnIgpSb3lhbEljaW5nDAsSDkNoYW5uZWxDb250ZW50GAQM/posts

###
GET {{host}}/1/org:RoyalIcing/channel:design/posts

###
GET {{host}}/1/org:RoyalIcing/channel:design/posts/aghkZXZ-Tm9uZXIxCxIDT3JnIgpSb3lhbEljaW5nDAsSDkNoYW5uZWxDb250ZW50GAEMCxIEUG9zdBgIDA

###
GET {{host}}/1/org:RoyalIcing/channel:design/posts.html

###
GET {{host}}/1/org:RoyalIcing/channel:engineering/posts
