@host = http://localhost:8080

###
GET {{host}}/

###
POST {{host}}/user-credentials

###
PUT http://localhost:8080/1/org:RoyalIcing
Content-Type: application/json

{}

###
PUT http://localhost:8080/1/org:RoyalIcing/channel:engineering
Content-Type: application/json

###
GET http://localhost:8080/1/org:RoyalIcing/channel:design

###
POST http://localhost:8080/1/org:RoyalIcing/channel:design/posts
Content-Type: application/json

{
  "markdownSource": "# This is a test!\n\n- A list\n- of\n- items\n"
}


###
GET http://localhost:8080/1/org:RoyalIcing/channel.id:aghkZXZ-Tm9uZXInCxIDT3JnIgpSb3lhbEljaW5nDAsSDkNoYW5uZWxDb250ZW50GAQM/posts

###
GET http://localhost:8080/1/org:RoyalIcing/channel:design/posts

###
GET http://localhost:8080/1/org:RoyalIcing/channel:engineering/posts
